"""
Django settings for webpapa project.

Generated by 'django-admin startproject' using Django 5.0.14
Configuración modular para entornos DEV/PRE/PROD.
"""

from pathlib import Path
import environ, os

# ══════════════════════════════════════════════════════════
# 🏗️ CONFIGURACIÓN BASE
# ══════════════════════════════════════════════════════════

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent   # …/dev/app

# Inicializa el entorno
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / '.env')

# Entorno actual
ENVIRONMENT = env("ENVIRONMENT", default="NONE")   # DEV / PRE / PROD

# ══════════════════════════════════════════════════════════
# 🔒 CONFIGURACIÓN DE SEGURIDAD
# ══════════════════════════════════════════════════════════

SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost'])
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# ══════════════════════════════════════════════════════════
# 📱 APLICACIONES INSTALADAS
# ══════════════════════════════════════════════════════════

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps', # ayuda al performance SEO
]

THIRD_PARTY_APPS = [
    # 🎨 UI y Formularios
    'crispy_forms',
    'crispy_bootstrap5',
    'widget_tweaks', # Para que funcione el |add_class y más cosas, se usa en formularios por ejemplo
    
    # 🏥 Monitoreo
    'health_check',
    'health_check.db',
    'health_check.cache',
    'health_check.storage',
]

LOCAL_APPS = [
    #'core.apps.CoreConfig', # esto falla, con importar 'core' es suficiente
    'core',                 # ← Debe ir siempre PRIMERO
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# 🔧 Solo en desarrollo
if DEBUG:
    INSTALLED_APPS += [
        'django_extensions',
        'debug_toolbar',
    ]

# ══════════════════════════════════════════════════════════
# 🔧 MIDDLEWARE
# ══════════════════════════════════════════════════════════

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 🔧 Solo en desarrollo
if DEBUG:
    MIDDLEWARE.insert(1, 'debug_toolbar.middleware.DebugToolbarMiddleware')

# ══════════════════════════════════════════════════════════
# 🌐 CONFIGURACIÓN DE URLs Y TEMPLATES
# ══════════════════════════════════════════════════════════

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'django.template.context_processors.i18n',  # ← COMENTAR por ahora, esto es par las traducciones
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# ══════════════════════════════════════════════════════════
# 🗄️ BASE DE DATOS
# ══════════════════════════════════════════════════════════

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ══════════════════════════════════════════════════════════
# 🔐 VALIDACIÓN DE CONTRASEÑAS
# ══════════════════════════════════════════════════════════

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ══════════════════════════════════════════════════════════
# 🌍 INTERNACIONALIZACIÓN
# ══════════════════════════════════════════════════════════

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Europe/Madrid'
USE_I18N = True
USE_L10N = True
USE_TZ = True
DEFAULT_CURRENCY = 'EUR'

# ❌ COMENTAR por ahora - ya se verá si se tendrá q traducir en un futuro...
# LANGUAGES = [
#     ('en', 'English'),
#     ('es', 'Español'),
# ]
# LOCALE_PATHS = [BASE_DIR / 'locale']

# ══════════════════════════════════════════════════════════
# 📁 ARCHIVOS ESTÁTICOS Y MEDIA
# ══════════════════════════════════════════════════════════

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # Fuente (va al repo)
STATIC_ROOT = BASE_DIR / 'staticfiles'    # Destino (NO va al repo)

# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# ══════════════════════════════════════════════════════════
# 🔐 AUTENTICACIÓN Y SESIONES
# ══════════════════════════════════════════════════════════

#LOGIN_REDIRECT_URL = '/dashboard/'
#LOGOUT_REDIRECT_URL = '/'

# Sessions en cache
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'sessions'
SESSION_COOKIE_AGE = 3600  # 1 hora
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = False  # Performance

# ══════════════════════════════════════════════════════════
# 🚀 CONFIGURACIÓN DE CACHE
# ══════════════════════════════════════════════════════════

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'webpapa-cache',
        'TIMEOUT': 300,  # 5 minutos
        'OPTIONS': {
            'MAX_ENTRIES': 2000,  # Más entradas
            'CULL_FREQUENCY': 3,
        },
        'KEY_PREFIX': 'webpapa',  # Prefijo
        'VERSION': 1,
    },
    'sessions': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'webpapa-sessions',
        'TIMEOUT': 86400,  # 24 horas
    }
}

# ══════════════════════════════════════════════════════════
# 📊 CONFIGURACIÓN DE LOGGING
# ══════════════════════════════════════════════════════════

# Crear directorio de logs si no existe
import os
if not os.path.exists(BASE_DIR / 'logs'):
    os.makedirs(BASE_DIR / 'logs')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',  # Rotación
            'filename': BASE_DIR / 'logs' / 'webpapa.log',
            'maxBytes': 1024*1024*10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple' if DEBUG else 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'core.middleware': {
            'handlers': ['file', 'console'] if DEBUG else ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'accounts': {
            'handlers': ['file', 'console'] if DEBUG else ['file', 'mail_admins'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.security': {
            'handlers': ['file', 'mail_admins'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
    'root': {
        'handlers': ['console'] if DEBUG else ['file'],
        'level': 'INFO',
    },
}

# ══════════════════════════════════════════════════════════
# 🎨 CONFIGURACIÓN DE THIRD-PARTY APPS
# ══════════════════════════════════════════════════════════

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# ══════════════════════════════════════════════════════════
# 🔧 CONFIGURACIÓN DE DESARROLLO
# ══════════════════════════════════════════════════════════

if DEBUG:
    # Debug Toolbar
    INTERNAL_IPS = [
        "127.0.0.1",
        "localhost",
        "172.18.0.1",  # Para Docker
    ]
    
    # Health Check opcional (comentado por ahora)
    # HEALTH_CHECK = {
    #     'DISK_USAGE_MAX': 90,  # Alert si disco >90%
    #     'MEMORY_MIN': 100,     # Alert si RAM <100MB
    # }

# ══════════════════════════════════════════════════════════
# � CONFIGURACIÓN DE EMAIL
# ══════════════════════════════════════════════════════════

# Email configuration - flexible para desarrollo y producción
if DEBUG:
    # En desarrollo: los emails se muestran en consola
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # En producción: Gmail SMTP gratuito
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='info@reformaselbosque.com')
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
    DEFAULT_FROM_EMAIL = env('EMAIL_HOST_USER', default='info@reformaselbosque.com')

# Configuración común para todos los entornos
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='Reformas El Bosque <contacto@gmail.com>')
EMAIL_SUBJECT_PREFIX = '[🏠 Nuevo Cliente - Reformas El Bosque] '
RECIPIENT_LIST = [env('ADMIN_EMAIL', default='tu_email_personal@gmail.com')]  # Tu email personal

# Para notificaciones de formulario de contacto
CONTACT_EMAIL_SUBJECT = 'Nueva consulta desde la web'
CONTACT_NOTIFICATION_EMAIL = env('ADMIN_EMAIL', default='tu_email_personal@gmail.com')

# ══════════════════════════════════════════════════════════
# 📝 CONFIGURACIONES FUTURAS (COMENTADAS)
# ══════════════════════════════════════════════════════════

# TODO: Configurar SSL para producción
# SECURE_SSL_REDIRECT = False

# TODO: Configurar Redis para cache en producción
# CACHES['default']['BACKEND'] = 'django.core.cache.backends.redis.RedisCache'

# ══════════════════════════════════════════════════════════
# 🏁 FIN DE CONFIGURACIÓN
# ══════════════════════════════════════════════════════════